[package]
name = "RockPaperScissorsLizardSpock"
version = "1.0.0"
authors = []

[addresses]
aptosgame = "0x24520160f6fec0a0ecf2a522c4538f34f7bc37927d89387d75b40157be335624"
std = "0x1"

[dev-addresses]
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]