[package]
name = "RockPaperScissorsLizardSpock"
version = "1.0.0"
authors = []

[addresses]
aptosgame = "YOUR_APTOS_WALLET_ADDRESS"
std = "0x1"

[dev-addresses]
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]